---
name: Bug Report
description: Report an issue with a template, plugin, or documentation
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue! Please fill out this template
        to help us understand and resolve the problem.

        **Before submitting**: Check the [Troubleshooting Guide](../../TROUBLESHOOTING.md)
        for common solutions.

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: Preliminary Checks
      options:
        - label: I have checked the Troubleshooting Guide
          required: true
        - label: I have searched existing issues for duplicates
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of LibreUIUX has the issue?
      options:
        - CLAUDE.md Template
        - Plugin (agent/skill/command)
        - Beginner Guide
        - Intermediate Guide
        - Advanced Guide
        - Setup Script
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: specific-file
    attributes:
      label: Specific File (if applicable)
      placeholder: e.g., templates/CLAUDE.modern-webapp.md

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What went wrong?
      placeholder: When I tried to..., Claude generated...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: I expected Claude to generate...
    validations:
      required: true

  - type: textarea
    id: prompt-used
    attributes:
      label: Prompt Used
      description: The exact prompt you used with Claude Code
      placeholder: |
        Create a button with...
    validations:
      required: true

  - type: textarea
    id: output-received
    attributes:
      label: Output Received
      description: What Claude actually generated (code or description)
      placeholder: Claude generated this code...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, environment details, or other relevant info
